[tool.poetry]
name = "hh-api"
version = "0.1.0"
description = ""
authors = ["Alexey Melnikov <stariy.melnik07@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
